### ISSUE TITLE
I would like assist to convert this app to bloc architecture

### ISSUE THREAD

**Issue by sheriffyusuf** [flutteryapps/habit_formation#1]
I have worked with blocs extensively and feel am suitable to do this task. Here's is a link to an on-going project I have used bloc with. https://github.com/sheriffyusuf/indistractable-launcher-clone

**Comment by flutteryapps** [comment]
Hey Sheriff,

I am glad that you want too contribute to this project. You can create a PR. I will review and merge it.

Thanks!
